document.querySelector("li").remove()
document.querySelector("span").remove()
document.querySelector(".posts article").remove()
let titles = document.querySelectorAll("h3")
titles.forEach((title) => title.remove())